### ISSUE TITLE
New Release for izpack

### ISSUE THREAD

**Issue by srbala** [izpack/izpack.github.io#23]
It has been more than two years since last release, when is the new release planned

**Comment by reinhapa** [comment]
@srbala working on the last issues, that i want to have in the release.

**Comment by srbala** [comment]
@reinhapa Thanks for the quick response. `izpack` has been great utility for java bundling and automation. Do you have any estimated timeline for the next release?

**Comment by reinhapa** [comment]
@srbala I can't give you an exact date but I planned to do a release around the beginning of 2021 after also moved the build over to Github actions.

**Comment by srbala** [comment]
Thanks for the update. I'll leave the issue open as tracker. Pleae close it when the new release published
