### ISSUE TITLE
Website izpack.org is down

### ISSUE THREAD

**Issue by maloewe-ona** [izpack/izpack.github.io#24]
The website https://izpack.org/ is down. Based on https://izpack.atlassian.net/browse/IZPACK-1735 this seems 'intended', however there are multiple issues:
- https://github.com/izpack/izpack.github.com
  - The GitHub "About" section still links to izpack.org
    ![About section screenshot](https://github.com/izpack/izpack.github.com/assets/138245828/34bbe547-b7ad-4571-8be5-343eced0f8d9)
  - The README still links to izpack.org
  - There are still a lot of references to izpack.org in the source code of this repository ([GitHub search query](https://github.com/search?q=repo%3Aizpack%2Fizpack.github.com+%22izpack.org%22+-language%3Axml&type=code))
  - The GitHub pages deployment still seems to be configured to deploy to izpack.org instead of izpack.github.io (in case that is desired)
- https://github.com/izpack/izpack
  - The GitHub "About" section still links to izpack.org
  - The README still links to izpack.org
  - There are still a lot of references to izpack.org in the source code of this repository ([GitHub search query](https://github.com/search?q=repo%3Aizpack%2Fizpack+%22izpack.org%22+-language%3Ajava+-language%3Axml&type=code)), including in the `pom.xml`
  - In case https://izpack.atlassian.net/wiki/spaces/IZPACK is the intended replacement, it might be good to mention it more prominently in the README, currently it is 'hidden' near the end in the README
    - Would be good to remove "izpack.org" references from the Confluence Wiki as well; for example directly the start page links to it

The links to izpack.org can also be problematic in case someone malicious takes over the domain.

Thanks a lot for maintaining the IzPack project!

**Comment by reinhapa** [comment]
@rkrell did you miss to renew the domain?
